---
- name: Copy opdracht2.txt to VM
  hosts: ubuntu_vms
  become: yes
  tasks:
    - name: Copy opdracht2.txt to /home/ubuntu/
      copy:
        src: ./Opdracht2.txt
        dest: /home/ubuntu/Opdracht2.txt
        owner: ubuntu
        group: ubuntu
        mode: '0644'
