---
- name: Backup /etc and /var/www daily
  hosts: week3vm
  become: yes
  tasks:
    - name: Create backup script
      copy:
        dest: /usr/local/bin/backup.sh
        content: |
          #!/bin/bash
          tar -czf /tmp/etc_www_backup_$(date +\%F).tar.gz /etc /var/www
        mode: '0755'

    - name: Add cronjob for daily backup
      cron:
        name: "Daily backup of /etc and /var/www"
        job: "/usr/local/bin/backup.sh"
        user: root
        minute: 0
        hour: 2
