---
- name: Add ESXi server entry to /etc/hosts
  hosts: week3vm
  become: yes
  tasks:
    - name: Add line to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "192.168.1.3 esxi"
        state: present
